from databricks.bundles.pipelines import Pipeline

# Generated by scripts/generate_resource.py. Do not edit manually.
template_domain_template_source_staging_basic_continuous = Pipeline.from_dict(
    {
        "catalog": "template_domain",
        "channel": "CURRENT",
        "configuration": {"pipeline_mode": "continuous", "source_system": "template_source"},
        "continuous": True,
        "development": True,
        "environment": {"dependencies": ["--editable ${workspace.file_path}"]},
        "libraries": [{"glob": {"include": "src/template_domain/template_source/staging/**"}}],
        "name": "template_domain_template_source_staging_basic_continuous",
        "root_path": "src/template_domain/template_source/staging",
        "schema": "template_source",
        "serverless": True,
        "tags": {"domain": "template_domain", "layer": "staging", "source": "template_source"},
    }
)
