from databricks.bundles.pipelines import Pipeline

# Generated by scripts/generate_resource.py. Do not edit manually.
finance_erp_full_core_streaming = Pipeline.from_dict(
    {
        "catalog": "finance",
        "channel": "CURRENT",
        "configuration": {
            "finance_erp_input_path": "/Volumes/finance/erp/raw/transactions",
            "finance_erp_schema_location": "/Volumes/finance/erp/checkpoints/autoloader_schema",
        },
        "continuous": True,
        "development": True,
        "environment": {"dependencies": ["--editable ${workspace.file_path}"]},
        "libraries": [
            {"glob": {"include": "src/finance/erp/raw/**"}},
            {"glob": {"include": "src/finance/erp/base/**"}},
            {"glob": {"include": "src/finance/erp/staging/**"}},
            {"glob": {"include": "src/finance/erp/final/**"}},
        ],
        "name": "finance_erp_full_core_streaming",
        "root_path": "src/finance/erp",
        "schema": "erp",
        "serverless": True,
        "tags": {"domain": "finance", "layer": "full", "source": "erp"},
    }
)
