targets:
  dev:
    mode: development
    default: true
    workspace:
      host: https://dbc-58f3d266-f942.cloud.databricks.com/
      root_path: /Workspace/Users/${workspace.current_user.userName}/.bundle/${bundle.name}/${bundle.target}
